server:
  port: 8082
  session:
    cookie:
      name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        #TODO: Task 4
        registration:
          private-client:
            client-id: booster-private-client
            client-name: Private Client
            client-authentication-method: basic
            client-secret:
            provider:
            redirect-uri:
            authorization-grant-type:
        #TODO: Task 9
#          public-client:
#            client-id: booster-public-client
#            client-name: Public Client with PKCE
        provider:
          custom-provider:
            token-uri: http://localhost:8081/auth/oauth/token
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            user-info-uri: http://localhost:8081/auth/user/me
            user-name-attribute: name